# GitHub Pages Configurations

title: Pages # The title of your site
# description: # A short description of your site's purpose
favicon: favicon.ico
manifest: manifest.json

# google_analytics: # Fill in your Google Analytics ID to track your website using Google Analytics

sass: # sass configurations
  style: compressed

exclude: # Exclude these files from production site
- "*.gemspec"
- README.md
- CONTRIBUTING.md
- CHANGELOG.md
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE.md

# plugins: # jekyll plugins
#  - jekyll-paginate
#  - jekyll-sitemap
