# GitHub Pages Configurations

title: Pages # The title of your site
# description: # A short description of your site's purpose

# google_analytics: # Fill in your Google Analytics ID to track your website using Google Analytics

sass:
  style: compressed

# Exclude these files from production site
exclude:
- "*.gemspec"
- README.md
- CONTRIBUTING.md
- CHANGELOG.md
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE.md

# Jekyll plugins
# plugins:
#  - jekyll-paginate
#  - jekyll-sitemap
